### ISSUE TITLE
Website menu texts font size (about, support, jobs, etc.)

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#1]
Text format and size is still not in line with all the other tabs and texts. Please make sure it is headline 16px and text 12px in the menu (about, jobs, terms conditions, etc.)

**Comment by multidimensionro** [comment]
@rcoppa The font size has been set as requested

**Comment by MaximilianArasin** [comment]
@rcoppa @multidimensionro 
Text format and size is still not in line with all the other tabs and texts. Please make sure it is headline 16px and text 12px in the menu (about, jobs, terms conditions, etc.) -->

Headline 16px and text 12px (this page is fine, please use it as a template for the other parts as requested above) also is it possible for me to go into <source> under pages and change the text content and spacing? The text is cut of and separated if we look at the lines ... not really sleek.
![screenshot_12](https://cloud.githubusercontent.com/assets/11382000/6769118/bed16c72-d08e-11e4-88ee-320f36b4cdfb.jpg)


Please use 16px for the headlines in bold and 12px for the text below (so that we have a consistent font size scheme through-out the entire website: 
![screenshot_13](https://cloud.githubusercontent.com/assets/11382000/6769152/bfdbcac6-d08f-11e4-907d-2342cf5c0c60.jpg)


Please add "Press" as a headline in bold and 16px and make the text 12px as on the other two pages above. Please also place the text in the middle and centered as per design (see "about" tab):
![screenshot_14](https://cloud.githubusercontent.com/assets/11382000/6769172/8628673e-d090-11e4-8ee7-348e26467fbd.jpg)


Please add "Jobs" as a headline in bold and 16px and make the text 12px (see above). Also entered and in the middle. I will also supply you with two link for job descriptions we would like to add. If we could just solve this like the business info sheet as a link and pdf that would be great.
![screenshot_15](https://cloud.githubusercontent.com/assets/11382000/6769207/ba4744da-d091-11e4-9248-85f0ba287ef5.jpg)

FAQ: Please use the same principles as above (headlines bold and 16px, text 12px
![screenshot_16](https://cloud.githubusercontent.com/assets/11382000/6769220/2be0e36c-d092-11e4-953b-7cefe2180a1c.jpg)


Terms & Conditions: Top headline to be capital letters is fine. Please do for the rest 16px headlines and bold and 12x for text as above. Please allow no gap between headlines and text.
![screenshot_17](https://cloud.githubusercontent.com/assets/11382000/6769235/d3faa4fc-d092-11e4-97f7-8bd3adece3ad.jpg)


Once this is done happy to close the issue guys.
Thanks a lot for this and best regards from 0 degrees Germany

**Comment by MaximilianArasin** [comment]
Hi @rcoppa @multidimensionro 

do we have any updates on this? I can see that parts of the issue have been solved and other parts haven't. 

Thanks a lot
cheers

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

This has been completed both on live and staging. Please review and if there are any other changes notify me.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
email link under PRESS doesn't work:

![screenshot_22](https://cloud.githubusercontent.com/assets/11382000/7063973/7a0fcd1a-deab-11e4-87a9-981f4c9de530.jpg)

**Comment by MaximilianArasin** [comment]
FAQ: the app keeps crashing --> headline to be the same size as the others please

![screenshot_23](https://cloud.githubusercontent.com/assets/11382000/7063994/dc577d9c-deab-11e4-98ff-7364ab32e3f2.jpg)

**Comment by MaximilianArasin** [comment]
terms & conditions: please see above. headlines and spacing as advised above please.

thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin 

We added the email action.

We added the correct size to the headline.

We checked the sizing of the hedlines and the text from the terms and conditions page. (headlines 16px; texts 12px)

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro great thx. Only issue remaining is spacing between headline and text on terms and conditions screen.
![screenshot_05](https://cloud.githubusercontent.com/assets/11382000/7157573/49619cb4-e371-11e4-9cf8-34b0275bdd0a.jpg)

to do as mentioned above: Leave top headline as it is but eliminate space between subheadlines and texts.

**Comment by MaximilianArasin** [comment]
Eligibility is correct.
User Account is correct.
Redemption of offers has space to be deleted underneath.

thx
