### ISSUE TITLE
HIGH PRIO: Additional text on initial page.

### ISSUE THREAD

**Issue by rcoppa** [DisruptSydney/Into#15]
First screen – email/password: we need to add a sentence: "Not a member? Into is a closed network. Apply for membership here." linked to http://getintoapp.com/index/membership  (to change in app and backend)

**Comment by MaximilianArasin** [comment]
I will meet Hardy on Monday/Tuesday and provide you with an updated png for this.

cheers

**Comment by MaximilianArasin** [comment]
@rcoppa We believe that this enhancement should be not additionally charged since it was originally part of Hardy design (login code screen). It is also not really an enhancement rather than a basic info/functionaity. Otherwise potential users who download the app have no possibility to navigate to our website to create a user account. It would be a dead end. Due to time and apple approval issues you used a different screen that we didn't approve with Hardy but you mentioned to worry about the final version later once we have the approval. I am sure you will understand. I will get Hardy to implement his text from the orifginal design to the new design and will supply you with the updated .png.

thx and cheers

**Comment by multidimensionro** [comment]
@MaximilianArasin 

I assume this is linked mostly to the app side. Please notify me when you have the final design and we will see how to move forward.

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro we updated the screen. This is now the final screen that would work even for potential users who do not have an account. We added the link (register your interest) to our website so that user can apply for a membership as we had it on the original designs. Please let me know if this works for you.

https://www.dropbox.com/s/45i1g7fa4l4ivy2/150407_designs_05.eps?dl=0
https://www.dropbox.com/s/e1s7296osr5jrts/150407_designs_05.png?dl=0

thanks a lot and cheers
Max

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

There may be an issue here with Apple, they may reject the app due to the registration process not handled inside the app ( the app was rejected before because of the same problem. They think that becoming a member requires payment and the payment is not done via AppStore ).

This is completed now. We will have to wait until the app review is completed to see if this is an issue.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
Hi @multidimensionro 
this might be the case indeed. We might have to handle the user application in-app. 
We might have to simply integrate this screen 

![screenshot_01](https://cloud.githubusercontent.com/assets/11382000/7165068/4ce9bc20-e3a5-11e4-89de-fffc78068c5f.jpg)

to the app. So that it is all handles within the app. That shouldn't be too complicated I hope.We could just do it with a flip screen like we do with "not sharing". Other apps like ASW are doing it the same way see here:

![img_7362](https://cloud.githubusercontent.com/assets/11382000/7165116/b8b97dfa-e3a5-11e4-83ac-e89907a8a822.PNG)
![img_7363](https://cloud.githubusercontent.com/assets/11382000/7165118/be49cd7e-e3a5-11e4-95dd-778388c3a848.PNG)
![img_7364](https://cloud.githubusercontent.com/assets/11382000/7165121/c28706b8-e3a5-11e4-96a1-d6323d2cd1e1.PNG)
