### ISSUE TITLE
HIGH PRIO: cloud animation doesn't fade out sometimes

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#20]
![animation](https://cloud.githubusercontent.com/assets/11382000/6983144/b89d9962-da1a-11e4-86c8-75f2268d9273.png)

**Comment by MaximilianArasin** [comment]
to do: please do some more testing and make sure that we don't have issues with the animation. On my phone it works fine though.

cheers and thx
Max

**Comment by multidimensionro** [comment]
@MaximilianArasin 

We have tested as much as we could on different devices with different iOS versions and we couldn't duplicate this bug. From this screenshot I can say that the issue is not at the clouds it is at the map because the clouds always stay over the map and if the clouds would be visible not map annotation can be seen.

Please offer us more details if possible.
