### ISSUE TITLE
HIGH PRIO: Paper plane – by clicking it, it says "coming soon"

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#22]
We should have the coming soon message only if the user clicks on a city (that is coming soon.linked to the city pop up menu) not paperplane. What if I am in a tiny german village? The paper plane finds me and it says coming soon while the closest city is displayed. But I am in a village that is definately not coming soon.

Please keep the "coming soon" pop up for the cities as it is. This works fine.

To do: Please disable the pop up "coming soon" when clicking the paper plane icon. No pop up needed when clicking the paper plane.

![paper plane coming soon pop up message](https://cloud.githubusercontent.com/assets/11382000/6985199/05e606d0-da31-11e4-836e-742342b78bc5.png)

**Comment by MaximilianArasin** [comment]
..also please make sure that the error message (coming soon) has the right size. We just tried it on an iPhone 6 and the pop up was way too small. Please match to the frame size of the cities:

![coming soon bug size](https://cloud.githubusercontent.com/assets/11382000/7025382/94010770-dd43-11e4-9552-c8a9fc7b8098.png)

cheers
Max

**Comment by multidimensionro** [comment]
@MaximilianArasin 

This issue is fixed now.
The problem here would be that the functionality for the paper plane button is, besides positioning the map at your current location, to auto-select the closest city from the cities menu. So, as per your example, if a user is in a tiny german village, the closest city from Cities list would be London, which is "Coming soon". We removed this alert for the case where the city is auto-selected because of the paper plane button ( user location ).

We are looking into the size issue.

**Comment by MaximilianArasin** [comment]
good.thx. also we should add Berlin as a city ...but this is backend related anyway.

cheers
