### ISSUE TITLE
low prio: Login procedure – if I use an email that has been used with another account – error message

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#23]
--> error message comes at the end of the procedure not already at the beginning. 

to do: can we please have this error message on the first screen where the users actually types in the email address and not 3 steps later when the users connects to their social networks.

![email used](https://cloud.githubusercontent.com/assets/11382000/6985348/bb06e9d4-da32-11e4-8c6a-948d257c394c.png)

thx and cheers

**Comment by multidimensionro** [comment]
@MaximilianArasin 

We are not sure if this error still exists because the login / register process has been changed. Now, the API checks if the email used in the login screen exists or not and only if it is not found in the database ( but the code used is a valid one ) sends the user to the register screen. So, this error should no longer appear at the end of the account set up. Our guess is that the screenshot was sent from an older version of the app.

Can you please double check this?

**Comment by MaximilianArasin** [comment]
@multidimensionro the screen shot came from my phone and I used the 1.0 version from th app store.
I will create a new account later and let you know if this still happens.

thx and cheers

**Comment by MaximilianArasin** [comment]
@multidimensionro  can we close?

**Comment by multidimensionro** [comment]
@MaximilianArasin yes this should not be possible to happen any longer as stated in my previous answer.

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

I think this could be closed.

Best regards,
Darius-Sorin Bodescu
