### ISSUE TITLE
low prio: Offer uploaded via fronted together with Darius via Skype - offer didn't show up in the app

### ISSUE THREAD

**Issue by MaximilianArasin** [DisruptSydney/Into#44]

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

I've discussed with Marcel and currently, the app refreshes the content only at login.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
So that means the user has to go into the menu then click log out then log in with email and password and then they see the new offers. 

That's a bit too much asked from the user I think. We want them to stay logged in of course. They might close the app by double click the home button ... But actively making the user log out. Not ideal ! What are your thoughts? What's there a reason for this? Sounds very new to me.

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin @rcoppa,

As provided by Marcel and including backend development changes we have the following options:

1) load each time the map loads - 1 business hour (only app side)- this is not recommended due to high mobile data consumption
2) load each time the map loads all deals since the last time they were loaded using a timestamp implementation (2hr app side  + 4hr api side) - this would provide live details every time without any delays
3) load every x hours - 2 business hours (only app side) - depending on how often "x hours" is this could provide a high mobile data consumption
4) load every x hours, but load only the new deals based on the last loaded timestamp - (3 business hours  app side + 4 business hours in API changes) - this will provide all the details every "x hours" with minimum mobile data consumpton.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
@multidimensionro what solution did we went with in the end? thx for the info...will close this issue once info received. thx

**Comment by multidimensionro** [comment]
Hi @MaximilianArasin,

The deals are being reloaded every day in full, so every 24hr. I think this was the last agreement we had.

Best regards,
Darius-Sorin Bodescu

**Comment by MaximilianArasin** [comment]
okay perfect ... I think so too. thx
